### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Shazgul** [tmb5cg/Fifa22-Autobidder#32]
```
PS E:\FIFA Autobidder> python src/main.py
USER SETTINGS DATE: 2022-06-24
TODAYS DATE: 2022-06-24
Dates match - will not clear GUI statistics
SYSTEM IS: Windows
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1378, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Can't start the Autobidder, because of this Error on Windows 10 with Python 3.10

**Comment by Shazgul** [comment]
Okay, after Re-Installing Python i'm getting a new Error:

`PS E:\FIFA Autobidder> python.exe .\src\main.py
USER SETTINGS DATE: 2022-06-24
TODAYS DATE: 2022-06-24
Dates match - will not clear GUI statistics
SYSTEM IS: Windows
Process Process-1:
Traceback (most recent call last):
  File "D:\Python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Python\lib\site-packages\undetected_chromedriver\dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "D:\Python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python\lib\subprocess.py", line 1378, in _execute_child
    args = list2cmdline(args)
  File "D:\Python\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "D:\Python\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by tmb5cg** [comment]
This is defo a python / system issue my brother. Give me a moment to think

**Comment by Shazgul** [comment]
Any new ideas?

**Comment by tmb5cg** [comment]
Look up how to install python on windows. You'll find a couple trash articles, but choose 3 of them and they'll probably be different, but do each. 

Sounds ridiculous but eventually one of them will work. Your error is definitely a system related python issue
